require "ruby_cover_band/amplifier"
require "ruby_cover_band/band"
require "ruby_cover_band/concert"
require "ruby_cover_band/instruments/drum"
require "ruby_cover_band/instruments/guitar"
require "ruby_cover_band/instruments/guitar/chords/chord"
require "ruby_cover_band/instruments/guitar/chords/b_flat_half_bar"
require "ruby_cover_band/instruments/guitar/chords/c_half_bar"
require "ruby_cover_band/instruments/guitar/chords/drop_d_low_d"
require "ruby_cover_band/instruments/guitar/chords/d_half_bar"
require "ruby_cover_band/instruments/guitar/chords/f_half_bar"
require "ruby_cover_band/instruments/guitar/chords/power_chord"
require "ruby_cover_band/instruments/guitar/finger_placement"
require "ruby_cover_band/instruments/guitar/fret"
require "ruby_cover_band/instruments/guitar/string"
require "ruby_cover_band/instruments/synthesizer"
require "ruby_cover_band/instruments/synthesizer/sound_bank"
require "ruby_cover_band/instruments/vocal"
require "ruby_cover_band/note"
require "ruby_cover_band/practice_amplifier"
require "ruby_cover_band/setlist"
require "ruby_cover_band/song"
require "ruby_cover_band/songs/the_line_begins_to_blur"
require "ruby_cover_band/version"

module RubyCoverBand
end
